### ISSUE TITLE
Should allow ftp through the proxy

### ISSUE THREAD

**Issue by diddledan** [canonical-websites/build.snapcraft.io#1057]
## Summary

Builds requiring sources hosted on an FTP server fail to build because the proxy doesn't allow the connection.

## Process

1. Add the following to a `snapcraft.yaml`:
```yaml
parts:
  alsa-lib:
    plugin: autotools
    source: ftp://ftp.alsa-project.org/pub/lib/alsa-lib-1.1.5.tar.bz2
```
2. upload to github in a project that is connected to the build service.
1. ...
1. watch Rome burn... and profit?

### expected
build succeeds

### actual
Death. Decay. Putrefaction. Or, a build failure.

## Log
```plain
Preparing to pull alsa-lib 
Pulling alsa-lib 
Downloading parts list                                                         
Downloading parts list                                                         
Downloading parts list                                                         
Downloading parts list                                                         
Downloading parts list                                                         
Downloading parts list                                                         
Downloading parts list                                                         
Downloading parts list                                                         
Downloading parts list                                                         
Downloading parts list                                                         
Downloading parts list                                                         
Downloading parts list                                                         
Downloading parts list                                                         
Downloading parts list                                                         
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1461, in ftp_open
    host = socket.gethostbyname(host)
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/snapcraft", line 9, in <module>
    load_entry_point('snapcraft==2.35', 'console_scripts', 'snapcraft')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/snapcraft/cli/__main__.py", line 19, in <module>
    run(prog_name='snapcraft')
  File "/usr/lib/python3/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3/dist-packages/snapcraft/cli/lifecycle.py", line 67, in pull
    _execute('pull', parts, **kwargs)
  File "/usr/lib/python3/dist-packages/snapcraft/cli/lifecycle.py", line 34, in _execute
    lifecycle.execute(command, project_options, parts)
  File "/usr/lib/python3/dist-packages/snapcraft/internal/lifecycle/_runner.py", line 80, in execute
    _Executor(config, project_options).run(step, part_names)
  File "/usr/lib/python3/dist-packages/snapcraft/internal/lifecycle/_runner.py", line 175, in run
    self._run_step(step, part, part_names)
  File "/usr/lib/python3/dist-packages/snapcraft/internal/lifecycle/_runner.py", line 212, in _run_step
    getattr(part, step)()
  File "/usr/lib/python3/dist-packages/snapcraft/internal/pluginhandler/__init__.py", line 251, in pull
    self.source_handler.pull()
  File "/usr/lib/python3/dist-packages/snapcraft/internal/sources/_base.py", line 55, in pull
    source_file = self.download()
  File "/usr/lib/python3/dist-packages/snapcraft/internal/sources/_base.py", line 89, in download
    download_urllib_source(self.source, self.file)
  File "/usr/lib/python3/dist-packages/snapcraft/internal/indicators.py", line 110, in download_urllib_source
    UrllibDownloader(uri, destination, message).download()
  File "/usr/lib/python3/dist-packages/snapcraft/internal/indicators.py", line 93, in download
    urlretrieve(self.uri, self.destination, self._progress_callback)
  File "/usr/lib/python3.5/urllib/request.py", line 188, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1463, in ftp_open
    raise URLError(msg)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
Build failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/lpbuildd/target/build_snap.py", line 225, in run
    self.pull()
  File "/usr/lib/python2.7/dist-packages/lpbuildd/target/build_snap.py", line 184, in pull
    env=env)
  File "/usr/lib/python2.7/dist-packages/lpbuildd/target/build_snap.py", line 88, in run_build_command
    return self.backend.run(args, cwd=cwd, env=full_env, **kwargs)
  File "/usr/lib/python2.7/dist-packages/lpbuildd/target/lxd.py", line 448, in run
    subprocess.check_call(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['lxc', 'exec', 'lp-xenial-amd64', '--env', 'LANG=C.UTF-8', '--env', 'SHELL=/bin/sh', '--env', 'SNAPCRAFT_LOCAL_SOURCES=1', '--env', 'SNAPCRAFT_SETUP_CORE=1', '--env', 'SNAPCRAFT_BUILD_INFO=1', '--env', 'http_proxy=http://snap-proxy.launchpad.net:3128', '--env', 'https_proxy=http://snap-proxy.launchpad.net:3128', '--env', 'GIT_PROXY_COMMAND=/usr/local/bin/snap-git-proxy', '--', '/bin/sh', '-c', 'cd /build/6ee01d1e891da75e9c9762fcafcb3c01-xenial && linux64 snapcraft pull']' returned non-zero exit status 1
Revoking proxy token...
RUN: /usr/share/launchpad-buildd/slavebin/in-target scan-for-processes --backend=lxd --series=xenial --arch=amd64 SNAPBUILD-141368
Scanning for processes to kill in build SNAPBUILD-141368
RUN: /usr/share/launchpad-buildd/slavebin/in-target umount-chroot --backend=lxd --series=xenial --arch=amd64 SNAPBUILD-141368
Stopping target for build SNAPBUILD-141368
RUN: /usr/share/launchpad-buildd/slavebin/in-target remove-build --backend=lxd --series=xenial --arch=amd64 SNAPBUILD-141368
```

**Comment by cjwatson** [comment]
This is already filed as https://bugs.launchpad.net/launchpad-buildd/+bug/1662613, which is the correct place for issues relating to the actual matter of running builds rather than the frontend.  Once that's fixed, there's nothing else to do in the build.snapcraft.io frontend, so I'm closing this bug.
