### ISSUE TITLE
Nock mocking started to fail in Travis

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/build.snapcraft.io#1063]
Recently travis tests started to fail because of some nock errors:

https://travis-ci.org/canonical-websites/build.snapcraft.io/builds/344272061
```
  1) Launchpad named_post handles successful response:
     FetchError: request to http://localhost:4000/launchpad/devel/people failed, reason: Nock: No match for request {
  "method": "POST",
  "url": "http://localhost:4000/launchpad/devel/people",
  "headers": {
    "authorization": [
      "OAuth oauth_consumer_key=\"consumer%20key\",oauth_nonce=\"0iqkcOvNlL6gRBJtEm74jLYw6IKbgUOm\",oauth_signature_method=\"PLAINTEXT\",oauth_timestamp=\"1519666546\",oauth_token=\"token%20key\",oauth_version=\"1.0\",oauth_signature=\"%26token%2520secret\""
    ],
    "content-type": [
      "application/x-www-form-urlencoded; charset=UTF-8"
    ],
    "accept-encoding": [
      "gzip,deflate"
    ],
    "user-agent": [
      "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
    ],
    "connection": [
      "close"
    ],
    "accept": [
      "*/*"
    ],
    "content-length": [
      13
    ]
  },
  "body": "ws.op=newTeam"
}
      at OverriddenClientRequest.<anonymous> (node_modules/node-fetch/index.js:133:11)
      at node_modules/nock/lib/request_overrider.js:223:11
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

**Comment by bartaz** [comment]
After some investigation it seems that in recently released version (that travis started to install because it's not locked in npm-shrinkwrap) they changed parsing of dot nested form params (such as `ws.op` that we use).

We should update the tests to accommodate to this change.

**Comment by bartaz** [comment]
Reported issue on nock about this, as many of our existing tests break because of this change: https://github.com/node-nock/nock/issues/1074
